<a href="https://colab.research.google.com/github/Veera-Divya/LogicMojo-AI-ML-April26-Divya1280/blob/main/pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
a= pd.Series([1,2,3,4,5,6])
print(a)
# set custom index
b=pd.Series([1,2,3,4,5,6], index=['a', 'b', 'c', 'd', 'e', 'f'])
print(b)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [ ]:
import pandas as pd
data = {'Name':['Alice', 'Divya'], 'age':[24,25], 'Salary': [50000, 60000]}
df = pd.DataFrame(data)
print(df)
df2 = pd.DataFrame([[1,2], [3,4]], columns =['A', 'B'])
print("df2\n", df2)
df3 = pd.DataFrame([[1]], columns =['A'])
print("df3\n", df3)

    Name  age  Salary
0  Alice   24   50000
1  Divya   25   60000
df2
    A  B
0  1  2
1  3  4
df3
    A
0  1

In [ ]:
print(df.index) #accessing index
print(df.columns) #accessing columns of data frame

RangeIndex(start=0, stop=2, step=1)
Index(['Name', 'age', 'Salary'], dtype='object')

In [ ]:
import pandas as pd
data = {'Name':['Alice', 'Divya'], 'age':[24,25], 'Salary': [50000, 60000]}
df = pd.DataFrame(data)
print("df:\n", df)
#first few rows of the data frame
print(df.head((5)))
print(df.head(1))


#display last few rows
print("tail :\n", df.tail(1))
print("tail :\n", df.tail(4))

df:
     Name  age  Salary
0  Alice   24   50000
1  Divya   25   60000
    Name  age  Salary
0  Alice   24   50000
1  Divya   25   60000
    Name  age  Salary
0  Alice   24   50000
tail :
     Name  age  Salary
1  Divya   25   60000
tail :
     Name  age  Salary
0  Alice   24   50000
1  Divya   25   60000

In [ ]:
# Purpose: Provides a concise summary of the DataFrame.
print(df.info())

# Purpose: Generates descriptive statistics of the DataFrame’s numerical columns.
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   age     2 non-null      int64
 2   Salary  2 non-null      int64
dtypes: int64(2), object(1)
memory usage: 180.0+ bytes
None
             age        Salary
count   2.000000      2.000000
mean   24.500000  55000.000000
std     0.707107   7071.067812
min    24.000000  50000.000000
25%    24.250000  52500.000000
50%    24.500000  55000.000000
75%    24.750000  57500.000000
max    25.000000  60000.000000

In [ ]:
# filtering data
print(df[df['age']> 20], end="\n\n")
print(df[df['age'].between(23, 24)], end="\n\n")
print(df[df['Name'].str.contains("iv")], end="\n\n")
print(df[df['Name'].str.startswith("Al")], end="\n\n")
print(df[df['Name'].str.endswith("ya")], end="\n\n")

    Name  age  Salary
0  Alice   24   50000
1  Divya   25   60000

    Name  age  Salary
0  Alice   24   50000

    Name  age  Salary
1  Divya   25   60000

    Name  age  Salary
0  Alice   24   50000

    Name  age  Salary
1  Divya   25   60000

In [ ]:
df.query('age > 24')  # Same as df[df['age'] > 24]

    Name  age  Salary
1  Divya   25   60000

In [ ]:
df[df['Name'].isin(['Alice', 'Bob'])]  # Selects rows where 'Name' is 'Alice' or 'Bob'

    Name  age  Salary
0  Alice   24   50000

In [ ]:
# df['New_Salary'] = df['Salary']*1.1
new_salary = df['Salary']*1.1

df.insert(1, 'New_Salary', new_salary)
print(df)

    Name  New_Salary  age  Salary
0  Alice     55000.0   24   50000
1  Divya     66000.0   25   60000

In [ ]:
df.drop('New_Salary', axis=1, inplace=True)
print(df)

    Name  age  Salary
0  Alice   24   50000
1  Divya   25   60000

In [ ]:
df.rename(columns={"Salary":"New_Salary"}, inplace=True)
print(df)

    Name  age  New_Salary
0  Alice   24       50000
1  Divya   25       60000

In [ ]:
df.rename(index={0: "Row_0"}, inplace=True)
print(df)

        Name  age  New_Salary
Row_0  Alice   24       50000
1      Divya   25       60000

In [ ]:
df.drop(1, axis=0, inplace=True)
print(df)

    Name  age  Salary
0  Alice   24   50000

In [ ]:
df.reindex([1,2])

    Name  New_Salary   age   Salary
1  Divya     66000.0  25.0  60000.0
2    NaN         NaN   NaN      NaN

In [ ]:
import pandas as pd
data = {'Name':['Alice', 'Divya'], 'age':[24,25], 'Salary': [50000, None]}
df = pd.DataFrame(data)
print(df)
print(df['age'].fillna(0, inplace=True))
print(df.fillna(0, inplace=True))

print(df)


import pandas as pd
data = {'Name':['Alice', 'Divya'], 'age':[24,25], 'Salary': [50000, None]}
df = pd.DataFrame(data)
df.dropna(inplace=True)
print(df)

    Name  age   Salary
0  Alice   24  50000.0
1  Divya   25      NaN
None
None
    Name  age   Salary
0  Alice   24  50000.0
1  Divya   25      0.0
    Name  age   Salary
0  Alice   24  50000.0

/tmp/ipykernel_2302/1336067968.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  print(df['age'].fillna(0, inplace=True))