<a href="https://colab.research.google.com/github/Veera-Divya/LogicMojo-AI-ML-April26-Divya1280/blob/main/panda_practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
s= pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
s= pd.Series([1,2,3,4,'a'])
s

0    1
1    2
2    3
3    4
4    a
dtype: object

In [5]:
s= pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
s.values

array([1, 2, 3, 4])

In [7]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
print(s.name)

None

In [9]:
s.name = "calories"
print(s.name)

calories

In [10]:
s[0]

np.int64(1)

In [11]:
s[0:2]

0    1
1    2
Name: calories, dtype: int64

In [12]:
s[[2,3]]

2    3
3    4
Name: calories, dtype: int64

In [13]:
# iloc -> location based indexing for nummerical indexes
s.iloc[3]

np.int64(4)

In [14]:
s.iloc[[1,2,3]]

1    2
2    3
3    4
Name: calories, dtype: int64

In [15]:
index = ["apple", "mango", "papaya", "banana"]
s.index = index
s

apple     1
mango     2
papaya    3
banana    4
Name: calories, dtype: int64

In [16]:
s['apple']

np.int64(1)

In [17]:
# loc -> label based indexing
s.loc["apple"]

np.int64(1)

In [18]:
# in label based indexing your start and stop value both are inclided in the output
s.loc["apple": "banana"]

apple     1
mango     2
papaya    3
banana    4
Name: calories, dtype: int64

In [19]:
s.dtype

dtype('int64')

In [20]:
s.loc[["apple", "banana"]]

apple     1
banana    4
Name: calories, dtype: int64

In [21]:
fruit_protien = {
    "Avocado": 2.0,
    "Apple": 2.0,
    "grape": 3.0,
    "strwaberry": 4.0
}
s=pd.Series(fruit_protien, name="protien")
s

Avocado       2.0
Apple         2.0
grape         3.0
strwaberry    4.0
Name: protien, dtype: float64

In [22]:
#Conditional statements
s>1

Avocado       True
Apple         True
grape         True
strwaberry    True
Name: protien, dtype: bool

In [23]:
#conditional selection
s[s>1]

Avocado       2.0
Apple         2.0
grape         3.0
strwaberry    4.0
Name: protien, dtype: float64

In [24]:
s[(s>0.5) & (s<=2)]

Avocado    2.0
Apple      2.0
Name: protien, dtype: float64

In [25]:
# modifying the series
s["Mango"] = 2.28
s

Avocado       2.00
Apple         2.00
grape         3.00
strwaberry    4.00
Mango         2.28
Name: protien, dtype: float64

In [26]:
# not operation
s=s[~(s>=3)]
s

Avocado    2.00
Apple      2.00
Mango      2.28
Name: protien, dtype: float64

In [27]:
dic = {
    "name":["Divya", "Arha", "Haritha"],
    "score":[2, 6, 7],
    "color":["Red", "Blue", "Green"]

}
df = pd.DataFrame(dic)
df

      name  score  color
0    Divya      2    Red
1     Arha      6   Blue
2  Haritha      7  Green

In [28]:
df.head()

      name  score  color
0    Divya      2    Red
1     Arha      6   Blue
2  Haritha      7  Green

In [29]:
df.head(2)

    name  score color
0  Divya      2   Red
1   Arha      6  Blue

In [30]:
df.tail(2)

      name  score  color
1     Arha      6   Blue
2  Haritha      7  Green

In [31]:
# loc and iloc
df.iloc[1:3]

      name  score  color
1     Arha      6   Blue
2  Haritha      7  Green

In [32]:
df.loc[1:3, ["score", "color"]]

   score  color
1      6   Blue
2      7  Green

In [33]:
df.drop('color', axis=1) #(inplace=True affect original df )

      name  score
0    Divya      2
1     Arha      6
2  Haritha      7

In [34]:
df

      name  score  color
0    Divya      2    Red
1     Arha      6   Blue
2  Haritha      7  Green

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   score   3 non-null      int64
 2   color   3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [36]:
df.describe()

          score
count  3.000000
mean   5.000000
std    2.645751
min    2.000000
25%    4.000000
50%    6.000000
75%    6.500000
max    7.000000

In [41]:
# Broadcasting
df["score"] = df["score"] + 6
df["score"]

0    32
1    36
2    37
Name: score, dtype: int64

In [45]:
# Renaming colums
df.rename(columns={"color": "COLOR"}, inplace=True)
df

      name  score  COLOR
0    Divya     32    Red
1     Arha     36   Blue
2  Haritha     37  Green

In [46]:
df["score"].unique()

array([32, 36, 37])

In [48]:
df["COLOR"].value_counts()

COLOR
Red      1
Blue     1
Green    1
Name: count, dtype: int64

In [51]:
df["promoted score"] = df["score"]*2
df

      name  score  COLOR  promoted score
0    Divya     32    Red              64
1     Arha     36   Blue              72
2  Haritha     37  Green              74

In [52]:
# Data cleaning
df.isnull().sum()

name              0
score             0
COLOR             0
promoted score    0
dtype: int64

In [65]:
dic = {
    "name":["Divya", "Arha", "Haritha", "Ram"],
    "score":[2, 6, 7, None],
    "color":["Red", "Blue", None, "Green", ]

}
df2 = pd.DataFrame(dic)
df2.head()

      name  score  color
0    Divya    2.0    Red
1     Arha    6.0   Blue
2  Haritha    7.0   None
3      Ram    NaN  Green

In [66]:
df2.dropna()

    name  score color
0  Divya    2.0   Red
1   Arha    6.0  Blue

In [67]:
df2.dropna(how="any") #by default it will be any

    name  score color
0  Divya    2.0   Red
1   Arha    6.0  Blue

In [68]:
df2.dropna(how="all") #all the values in row should be none to be dropped

      name  score  color
0    Divya    2.0    Red
1     Arha    6.0   Blue
2  Haritha    7.0   None
3      Ram    NaN  Green

In [70]:
df2.fillna(0) #value must be provided

      name  score  color
0    Divya    2.0    Red
1     Arha    6.0   Blue
2  Haritha    7.0      0
3      Ram    0.0  Green

In [71]:
df2["score"].fillna(df2["score"].mean()) #value must be provided

0    2.0
1    6.0
2    7.0
3    5.0
Name: score, dtype: float64

In [75]:
df2["color"].fillna(method="bfill")

/tmp/ipykernel_1790/3604501198.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2["color"].fillna(method="bfill")

0      Red
1     Blue
2    Green
3    Green
Name: color, dtype: object

In [76]:
df2["color"].fillna(method="ffill")

/tmp/ipykernel_1790/619994790.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2["color"].fillna(method="ffill")

0      Red
1     Blue
2     Blue
3    Green
Name: color, dtype: object

In [77]:
df2["name"].replace("Arha", "Joshi") # to replcae  a particulat value

0      Divya
1      Joshi
2    Haritha
3        Ram
Name: name, dtype: object

In [89]:
# Duplicates:
dic = {
    "name":["Divya", "Divya", "Haritha", "Ram"],
    "score":[2, 2, 7, None],
    "color":["Red", "Red", None, "Green", ]

}
df2 = pd.DataFrame(dic)
df2.head()
df_dup = df2[df2.duplicated]
df_dup
df_dup = df2[df2.duplicated(keep="first")]
df_dup

    name  score color
1  Divya    2.0   Red

In [91]:
df2.drop_duplicates()

      name  score  color
0    Divya    2.0    Red
2  Haritha    7.0   None
3      Ram    NaN  Green

In [95]:
df2

      name  score  color
0    Divya   2.00    Red
1    Divya   2.00    Red
2  Haritha   1.75   None
3      Ram    NaN  Green

In [96]:
#invalid values
#Lambda -> Python
df2
df2["score"]=df2["score"].apply(lambda x:x/2 if x>=2 else x)
df2

      name  score  color
0    Divya   1.00    Red
1    Divya   1.00    Red
2  Haritha   1.75   None
3      Ram    NaN  Green

In [110]:
dic = {
    "name":["Divya", "Divya", "Haritha", "Ram"],
    "score":[2, 2, 7, None],
    "color":["Red", "Red", None, "Green", ]

}
df2 = pd.DataFrame(dic)
df2["name"].replace("Divya", "Divya_Reddy", inplace=True)
df2.head()

/tmp/ipykernel_1790/2046882593.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["name"].replace("Divya", "Divya_Reddy", inplace=True)

          name  score  color
0  Divya_Reddy    2.0    Red
1  Divya_Reddy    2.0    Red
2      Haritha    7.0   None
3          Ram    NaN  Green

In [111]:
df2["first_name", "last_name"] = df2["name"].str.split("_")
df2

          name  score  color (first_name, last_name)
0  Divya_Reddy    2.0    Red          [Divya, Reddy]
1  Divya_Reddy    2.0    Red          [Divya, Reddy]
2      Haritha    7.0   None               [Haritha]
3          Ram    NaN  Green                   [Ram]

In [113]:
#apply and lamda

def multpily(x):
  return x*2
df2["score"] = df2["score"].apply(multpily)
df2

          name  score  color (first_name, last_name)
0  Divya_Reddy    4.0    Red          [Divya, Reddy]
1  Divya_Reddy    4.0    Red          [Divya, Reddy]
2      Haritha   14.0   None               [Haritha]
3          Ram    NaN  Green                   [Ram]

In [116]:
df2["score"] = df2["score"].apply(lambda x: x/2)
df2

          name  score  color (first_name, last_name)
0  Divya_Reddy    2.0    Red          [Divya, Reddy]
1  Divya_Reddy    2.0    Red          [Divya, Reddy]
2      Haritha    7.0   None               [Haritha]
3          Ram    NaN  Green                   [Ram]

In [125]:
dic = {
    "name":["Divya", "Divya", "Haritha", "Ram"],
    "score1":[2, 2, 7, None],
    "color1":["Red", "Red", None, "Green", ]

}
df2 = pd.DataFrame(dic)
df2.head()

      name  score1 color1
0    Divya     2.0    Red
1    Divya     2.0    Red
2  Haritha     7.0   None
3      Ram     NaN  Green

In [120]:
# Joins
#left right outer inner merge joins
pd.concat([df2, df])

,name1,score1,color1,name,score,COLOR,promoted score,"(first_name, last_name)"
0,Divya,2.0,Red,NaN,NaN,NaN,NaN,NaN
1,Divya,2.0,Red,NaN,NaN,NaN,NaN,NaN
2,Haritha,7.0,None,NaN,NaN,NaN,NaN,NaN
3,Ram,NaN,Green,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,Divya,32.0,Red,64.0,[Divya]
1,NaN,NaN,NaN,Arha,36.0,Blue,72.0,[Arha]
2,NaN,NaN,NaN,Haritha,37.0,Green,74.0,[Haritha]

In [123]:
pd.concat([df2, df], axis=1)

,name1,score1,color1,name,score,COLOR,promoted score,"(first_name, last_name)"
0,Divya,2.0,Red,Divya,32.0,Red,64.0,[Divya]
1,Divya,2.0,Red,Arha,36.0,Blue,72.0,[Arha]
2,Haritha,7.0,None,Haritha,37.0,Green,74.0,[Haritha]
3,Ram,NaN,Green,NaN,NaN,NaN,NaN,NaN

In [126]:
pd.merge(df2, df, on="name")

,name,score1,color1,score,COLOR,promoted score,"(first_name, last_name)"
0,Divya,2.0,Red,32,Red,64,[Divya]
1,Divya,2.0,Red,32,Red,64,[Divya]
2,Haritha,7.0,None,37,Green,74,[Haritha]

In [ ]:
#importing file
data = pd.read_csv("data.csv`")