<a href="https://colab.research.google.com/github/Veera-Divya/LogicMojo-AI-ML-April26-Divya1280/blob/main/pandas_assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['Vinay', 'Kushal', 'Aman', 'Saif'], 'age': [22, 25, 24,
28], 'occupation': ['engineer', 'doctor', 'data analyst', 'teacher']})
print(df)

     name  age    occupation
0   Vinay   22      engineer
1  Kushal   25        doctor
2    Aman   24  data analyst
3    Saif   28       teacher

In [ ]:
print(df.head())

     name  age    occupation
0   Vinay   22      engineer
1  Kushal   25        doctor
2    Aman   24  data analyst
3    Saif   28       teacher

In [ ]:
print(df.head(2))

     name  age occupation
0   Vinay   22   engineer
1  Kushal   25     doctor

In [ ]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=4, step=1)
Index(['name', 'age', 'occupation'], dtype='object')

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   age         4 non-null      int64
 2   occupation  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes
None

In [ ]:
df.describe()

         age
count   4.00
mean   24.75
std     2.50
min    22.00
25%    23.50
50%    24.50
75%    25.75
max    28.00

In [ ]:
(df['age'])

0    22
1    25
2    24
3    28
Name: age, dtype: int64

In [ ]:
df.age

0    22
1    25
2    24
3    28
Name: age, dtype: int64

In [ ]:
df[['age', 'name']]

   age    name
0   22   Vinay
1   25  Kushal
2   24    Aman
3   28    Saif

In [ ]:
df[1:2]

     name  age occupation
1  Kushal   25     doctor

In [ ]:
df[1:4]

     name  age    occupation
1  Kushal   25        doctor
2    Aman   24  data analyst
3    Saif   28       teacher

In [ ]:
df[2::2]

   name  age    occupation
2  Aman   24  data analyst

In [ ]:
print(df, end="\n\n")
print(df.iloc[2,2], end="\n\n")
print(df.iloc[2,1], end="\n\n")

     name  age    occupation
0   Vinay   22      engineer
1  Kushal   25        doctor
2    Aman   24  data analyst
3    Saif   28       teacher

data analyst

24

In [ ]:
df.iloc[1:3,0:2]

     name  age
1  Kushal   25
2    Aman   24

In [ ]:
df.iloc[3]

name             Saif
age                28
occupation    teacher
Name: 3, dtype: object

In [ ]:
df.iloc[2, 1:2]

age    24
Name: 2, dtype: object

In [ ]:
df.iloc[[1,2]]

     name  age    occupation
1  Kushal   25        doctor
2    Aman   24  data analyst

In [ ]:
df.iloc[1]

name          Kushal
age               25
occupation    doctor
Name: 1, dtype: object

In [ ]:
df.iloc[[1]]

     name  age occupation
1  Kushal   25     doctor

In [ ]:
print(df.loc[2,'name'])

Aman

In [ ]:
print(df.loc[[1,3], "name":"age"])

     name  age
1  Kushal   25
3    Saif   28

In [ ]:
print(df.loc[1:3, "name":"age"])

     name  age
1  Kushal   25
2    Aman   24
3    Saif   28

In [ ]:
print(df.loc[:, "name":"age"])

     name  age
0   Vinay   22
1  Kushal   25
2    Aman   24
3    Saif   28

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Copy of BikeIndia.csv')
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [ ]:

## Create a df from the above df which has only numerical columns

df2 = df.select_dtypes(include=['int64', 'float64'])
df2.head()

,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,
1,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
2,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
3,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
4,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
5,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     730 non-null    int64
 1   dteday      730 non-null    object
 2   season      730 non-null    int64
 3   yr          730 non-null    int64
 4   mnth        730 non-null    int64
 5   holiday     730 non-null    int64
 6   weekday     730 non-null    int64
 7   workingday  730 non-null    int64
 8   weathersit  730 non-null    int64
 9   temp        730 non-null    float64
 10  atemp       730 non-null    float64
 11  hum         730 non-null    float64
 12  windspeed   730 non-null    float64
 13  casual      730 non-null    int64
 14  registered  730 non-null    int64
 15  cnt         730 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.4+ KB

In [ ]:
df.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000
mean,365.500000,2.498630,0.500000,6.526027,0.028767,2.997260,0.683562,1.394521,20.319259,23.726322,62.765175,12.763620,849.249315,3658.757534,4508.006849
std,210.877136,1.110184,0.500343,3.450215,0.167266,2.006161,0.465405,0.544807,7.506729,8.150308,14.237589,5.195841,686.479875,1559.758728,1936.011647
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.424346,3.953480,0.000000,1.500244,2.000000,20.000000,22.000000
25%,183.250000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,13.811885,16.889713,52.000000,9.041650,316.250000,2502.250000,3169.750000
50%,365.500000,3.000000,0.500000,7.000000,0.000000,3.000000,1.000000,1.000000,20.465826,24.368225,62.625000,12.125325,717.000000,3664.500000,4548.500000
75%,547.750000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,26.880615,30.445775,72.989575,15.625589,1096.500000,4783.250000,5966.000000
max,730.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,35.328347,42.044800,97.250000,34.000021,3410.000000,6946.000000,8714.000000

In [ ]:
df.loc[2:6, 'windspeed': 'registered']

   windspeed  casual  registered
2  16.636703     120        1229
3  10.739832     108        1454
4  12.522300      82        1518
5   6.000868      88        1518
6  11.304642     148        1362

   windspeed  registered
0  10.749882         654
1  16.652113         670
2  16.636703        1229
3  10.739832        1454
4  12.522300        1518
5   6.000868        1518
6  11.304642        1362

In [ ]:
df.set_index('instant', inplace=True)
df.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [ ]:
df2 = df[df['windspeed']>10][['windspeed', 'atemp', 'temp']]
df2.head()

         windspeed     atemp       temp
instant
1        10.749882  18.18125  14.110847
2        16.652113  17.68695  14.902598
3        16.636703   9.47025   8.050924
4        10.739832  10.60610   8.200000
5        12.522300  11.46350   9.305237

In [ ]:
df.shape

(730, 15)

In [ ]:
df2.shape

(488, 3)

In [ ]:
df3 = pd.merge(df, df2, how='left', on=['temp', 'atemp'])
df3.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed_x,casual,registered,cnt,windspeed_y
0,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985,10.749882
1,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801,16.652113
2,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,16.636703
3,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,10.739832
4,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,12.522300

In [ ]:
df2 = df[df['windspeed']>10][['windspeed', 'atemp', 'casual']]
df2.head()

         windspeed     atemp  casual
instant
1        10.749882  18.18125     331
2        16.652113  17.68695     131
3        16.636703   9.47025     120
4        10.739832  10.60610     108
5        12.522300  11.46350      82

In [ ]:
df3 = pd.merge(df, df2, how='left', on=['atemp', 'windspeed'])
df3.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual_x,registered,cnt,casual_y
0,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985,331.0
1,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801,131.0
2,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,120.0
3,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,108.0
4,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,82.0